<?php

namespace AdminBundle\Repository;

/**
 * BlagueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlagueRepository extends \Doctrine\ORM\EntityRepository
{
}
